# Generated by Django 4.2.23 on 2025-07-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
