# Generated by Django 4.2.23 on 2025-07-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0003_alter_casestudy_client_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Client_list',
        ),
    ]
