# Generated by Django 4.2.23 on 2025-07-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0004_rename_client_client_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_list',
            new_name='Client',
        ),
    ]
